### ISSUE TITLE
is a .pdf version available for this?

### ISSUE THREAD

**Issue by Maoni0** [weiminye/pro-dotnet-memory-mgr-translation-review#100]
hello WeiMin, thanks for translating this book to Chinese. I am the architect for the GC described in the book. I was hoping I could purchase a .pdf copy of the Chinese version from you. would that be possible? 谢谢您.

**Comment by weiminye** [comment]
Hi Maoni,

I am so sorry I can not send you the PDF version because there is no PDF version published by TSingHua University Press.

Only paper book on sale at [jd.com](https://union-click.jd.com/jdc?e=&p=JF8AALYDIgZlGmsVARsFXRpSHTJWWA1FBCVbV0IUWVALHEpCAUdETlcNVQtHRRUBGwVdGlIdHUtCCUZraBx5QgBTDWFnQXUsc192ZFtANx0AUw4eN1QrWxQDEQFcH10dASI3VRxrXmwTN1QrWxIBEwJTElwdCxYFUitcFQsiBFEbUx0HGgFQG2slMhE3ZStbJQEiRTsfUhIGGw5RTF9HBhQCAhlYRVcRAQEaDx1QQlUGHQscUSIFVBpfHA) & dangdang.com

Thanks your work at .NET GC

**Comment by Maoni0** [comment]
ok thanks for your answer.
